version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      npm-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      actions:
        patterns:
          - "*"


  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
