name: Test

on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true

jobs:
  test:
    name: Tester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3.6.0
      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - name: Installere moduler
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Kjøre tester
        run: npm test --maxWorkers=2
